language: node_js

node_js:
- '0.12'

before_install:
- npm install --quiet -g grunt
- npm config registries.github.auth JoDDiz9yYoTiqxwqtcy8
- bower install


script:
- grunt

cache:
  directories:
  - ./node_modules
  - ./bower_components